# -*- coding: utf-8 -*-
"""Candlestick_Chart.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1s5Wq0rCZkzRSdDDKDtq55qq2-tV8kYZa
"""

#Resource:
#Candlestick Charts in Python: https://plot.ly/python/candlestick-charts/#simple-example-with-datetime-objects

#Import the libraries
import plotly.graph_objects as go
import pandas as pd
from datetime import datetime
from pandas_datareader import data as web

# Get the stocks ending date aka todays date and format it in the form YYYY-MM-DD
today = datetime.today().strftime('%Y-%m-%d')

df = web.DataReader('ZOM', data_source='yahoo',
                               start='2013-01-01' , end=today)

df['Date'] = df.index

fig = go.Figure(data=[go.Candlestick(x=df['Date'],
                open=df['Open'],
                high=df['High'],
                low=df['Low'],
                close=df['Close'],
                increasing_line_color= 'gold', decreasing_line_color= 'black'
                
                )])

fig.show()